package com.wiryadev.binar_movie_compose.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF894587)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFffd6f9)
val md_theme_light_onPrimaryContainer = Color(0xFF37003b)
val md_theme_light_secondary = Color(0xFF6d5869)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFf7dbf0)
val md_theme_light_onSecondaryContainer = Color(0xFF261625)
val md_theme_light_tertiary = Color(0xFF815246)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFffdad0)
val md_theme_light_onTertiaryContainer = Color(0xFF321209)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfcfcfc)
val md_theme_light_onBackground = Color(0xFF1e1b1d)
val md_theme_light_surface = Color(0xFFfcfcfc)
val md_theme_light_onSurface = Color(0xFF1e1b1d)
val md_theme_light_surfaceVariant = Color(0xFFeedee8)
val md_theme_light_onSurfaceVariant = Color(0xFF4d444b)
val md_theme_light_outline = Color(0xFF80747c)
val md_theme_light_inverseOnSurface = Color(0xFFf8eef2)
val md_theme_light_inverseSurface = Color(0xFF342f32)
val md_theme_light_inversePrimary = Color(0xFFfcabf5)
val md_theme_light_shadow = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFfcabf5)
val md_theme_dark_onPrimary = Color(0xFF531355)
val md_theme_dark_primaryContainer = Color(0xFF6e2c6e)
val md_theme_dark_onPrimaryContainer = Color(0xFFffd6f9)
val md_theme_dark_secondary = Color(0xFFd9bfd3)
val md_theme_dark_onSecondary = Color(0xFF3c2b3a)
val md_theme_dark_secondaryContainer = Color(0xFF544151)
val md_theme_dark_onSecondaryContainer = Color(0xFFf7dbf0)
val md_theme_dark_tertiary = Color(0xFFf5b8a9)
val md_theme_dark_onTertiary = Color(0xFF4c261c)
val md_theme_dark_tertiaryContainer = Color(0xFF663b30)
val md_theme_dark_onTertiaryContainer = Color(0xFFffdad0)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF1e1b1d)
val md_theme_dark_onBackground = Color(0xFFe9e0e4)
val md_theme_dark_surface = Color(0xFF1e1b1d)
val md_theme_dark_onSurface = Color(0xFFe9e0e4)
val md_theme_dark_surfaceVariant = Color(0xFF4d444b)
val md_theme_dark_onSurfaceVariant = Color(0xFFd1c3cc)
val md_theme_dark_outline = Color(0xFF998d95)
val md_theme_dark_inverseOnSurface = Color(0xFF1e1b1d)
val md_theme_dark_inverseSurface = Color(0xFFe9e0e4)
val md_theme_dark_inversePrimary = Color(0xFF894587)
val md_theme_dark_shadow = Color(0xFF000000)



val seed = Color(0xFF894587)
val error = Color(0xFFba1b1b)